export { CloudscapeThemeProvider } from '../component/cloudscape/CloudscapeThemeProvider'
export { cloudscapeTheme } from '../component/cloudscape/cloudscapeTheme'
export { boardItemI18nStrings, createBoardI18nStrings } from '../component/cloudscape/boardI18n'
export { CloudscapeBoardStyles } from '../component/cloudscape/CloudscapeBoardStyles'
export * from '../component/widget-board'
